[package]
name = "rung"
version = "0.1.0"
description = "Rung — a capital-backed valuation market for PreStocks on Solana"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "rung"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = { version = "1.2.0", features = ["init-if-needed"] }
anchor-spl = { version = "1.2.0", features = ["token_2022"] }
